---
name: Molecule tests
on:
  push:
    branches:
      - main
    paths_ignore:
      - '*.md'
      - '.ansible-lint'
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths_ignore:
      - '*.md'
      - '.ansible-lint'

jobs:

  molecule:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_FORCE_COLOR: '0' # ANSI coloring breaks GitHub's ability to mask tokens in logs.
      ANSIBLE_RESULT_FORMAT: yaml
      REQUIREMENTS_FILE: molecule/ext/molecule-src/requirements.txt
      GALAXY_REQUIREMENTS_FILE: molecule/ext/molecule-src/requirements.yml
      MOLECULE_FILE: molecule/ext/molecule-src/molecule.yml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r ${{ env.REQUIREMENTS_FILE }}
      - run: ansible-galaxy install -r ${{ env.GALAXY_REQUIREMENTS_FILE }}
      - name: Molecule tests
        run: |
          molecule -vvv -c ${{ env.MOLECULE_FILE }} test --all
